# markdown: "kramdown"

plugins: 
  - "jekyll-paginate"
permalink: "pretty"

title: "iRISC Research Syndicate"
description: "Reverse engineering the NVIDIA/Mellanox iRISC ConnectX-5 FIrmware"

baseurl: "/"

paginate: 5
paginate_path: "/blog/page:num/"